myapp/forms/__init__.py
from .login_forms import LoginForm,RegisterForm

myapp/forms/login_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField
from wtforms.validators import DataRequired,EqualTo,ValidationError

from ..users import exists_username


class LoginForm(FlaskForm):

	username = StringField(id='username',validators=[DataRequired(message="Username is required")])
	passwd = PasswordField(id='passwd',validators=[DataRequired(message="Password is required")])



class RegisterForm(FlaskForm):
	
	username = StringField(id='username',validators=[DataRequired(message="Username is required")])
	passwd = PasswordField(id='passwd',validators=[DataRequired(message="Password is required")])
	passwd2 = PasswordField(id='passwd2',validators=[DataRequired(message="Password re-typing is required"),
												     EqualTo('passwd',message="Re-typed password does not match")])

	def validate_username(self,username):
		""" a custom validator for username, raising error
		if username already exists in user db """
		
		if exists_username(username.data):
			raise ValidationError("Username already exists") 
			

myapp/__init__.py
from .app import app

myapp/app.py
import os

from flask import Flask
from werkzeug.contrib.fixers import ProxyFix
from flask_pymongo import PyMongo
from flask_login import LoginManager

def create_app():


	# common prefix for all routes in blueprints
	APP_URL_PREFIX = os.environ.get('MY_APP_PREFIX',None)

	# common prefix will also be prefix for static files
	APP_STATIC_URL = '/static'
	if APP_URL_PREFIX:
		APP_STATIC_URL = APP_URL_PREFIX + APP_STATIC_URL 
	
	app = Flask(__name__,static_url_path=APP_STATIC_URL)
	# important: use the following to respect X-Forwarded-Proto when https!
	app.wsgi_app = ProxyFix(app.wsgi_app)
			
	# app prefix will be used also for open redirect attempts detection
	app.config['REDIRECT_PREFIX'] = APP_URL_PREFIX+'/'
	
	# secret key of application
	app.config['SECRET_KEY'] = os.environ['MY_APP_SECRET_KEY']
	
		
	# mongodb database name
	app.config['MONGO_DBNAME'] = os.environ.get('MY_APP_MONGODB_NAME',app.name)
	# configure mongo
	mongo.init_app(app)
	
	
	# register all blueprints
	from .views import blueprints
	for bp in blueprints:
		app.register_blueprint(bp,url_prefix=APP_URL_PREFIX)


	# configure login_manager
	login_manager.init_app(app)
	login_manager.login_view = 'login.login_page'	

		
	return app

	
mongo = PyMongo()
login_manager = LoginManager() 
app = create_app()	
	

myapp/users/__init__.py
from .users import register_user,exists_username,validate_user

myapp/views/__init__.py
from .hello import hello
from .login import login

blueprints = [hello,login]

myapp/views/hello.py
from flask import Blueprint,render_template
from flask_login import login_required
from pymongo import ReturnDocument

from ..app import mongo


hello = Blueprint('hello',__name__)


@hello.route('/')
@login_required
def index_page():

	return render_template('index.html')
	

@hello.route('/other')
@login_required
def other_page():

	return render_template('other.html')

myapp/views/login.py
from flask import Blueprint,render_template,redirect,url_for,request,current_app,flash
from pymongo import ReturnDocument
from flask_login import login_user,logout_user,current_user,login_required

from ..app import mongo
from ..forms import RegisterForm,LoginForm
from ..users import register_user,validate_user


login = Blueprint('login',__name__)


@login.route('/login',methods=['GET','POST'])
def login_page():

	# if user is already logged in, redirect to index page
	if current_user.is_authenticated:
		return redirect(url_for('hello.index_page'))

	form = LoginForm()
	
	cred_error = False
	if form.validate_on_submit():
		# check user's existence/credentials
		user = validate_user(form.username.data,form.passwd.data)
		if user:
			login_user(user)
			
			# check if next parameter dictates specific redirect
			next = request.args.get('next')
			# IMPORTANT NOTE: next must be checked for open redirect attempts!
			# Python's urlparse can be tricked to perceive an external redirect as an internal one!
			# Here we check that next string starts exactly with /APP_PREFIX/
			if next and next.startswith(current_app.config['REDIRECT_PREFIX']):
				return redirect(next) 
			
			# no next parameter or next parameter has illegal value
			return redirect(url_for('hello.index_page'))
	
		# user provided invalid credentials
		cred_error = True
		
	return render_template('login.html',form=form,cred_error=cred_error)


@login.route('/register',methods=['GET','POST'])
def register_page():

	# if user is already logged in, redirect to index page
	if current_user.is_authenticated:
		return redirect(url_for('hello.index_page'))

	form = RegisterForm()
	
	if form.validate_on_submit():
		# register new user
		user = register_user(form.username.data,form.passwd.data)
		# if registration ok (should nornally be), log the new user in
		if user is not None:
			login_user(user)
			# redirect to index page
			return redirect(url_for('hello.index_page'))
	
	return render_template('register.html',form=form)


@login.route('/logout')
@login_required
def logout_page():
	logout_user()
	return redirect(url_for('login.login_page'))

myapp/templates/index.html
<!DOCTYPE html>
<html lang="el">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <link rel="stylesheet" href="static/bootstrap.min.css">
  </head>
  <body>
  <div class="row">
  <div class="col-md-6 offset-md-3">
  <h4>Index page</h4>
  <p>
  User: {{ current_user.user_record['username']|safe}}
  </p>
  <p>
  Check <a href="{{ url_for("hello.other_page") }}">another</a> page!
  </p>
  <p>
  <a class="btn btn-primary" href="{{ url_for("login.logout_page") }}">Logout</a>
  </p>
  </div>
  </div>
  </body>
</html>

myapp/templates/login.html
<!DOCTYPE html>
<html lang="el">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <link rel="stylesheet" href="static/bootstrap.min.css">
  </head>
  <body>
  <div class="row">
  <div class="col-md-6 offset-md-3">
  <h4>User Login</h4>
  <form method="POST" action="">
    {{ form.hidden_tag() }}    {# this takes care of Flask-WTF csrf token too #}
    <div class="form-group">
      {{ form.username(**{'class':'form-control','aria-describedby':'userhlp','placeholder':'Username'}) }}
      {% if form.username.errors %}
      <ul class="form-text text-danger">
      {% for error in form.username.errors %}<li>{{ error }}</li>{% endfor %}
      </ul>
      {% else %} 
      <small id=userhlp" class="form-text text-muted">Enter your username.</small>
      {% endif %}
    </div>

    <div class="form-group">
      {{ form.passwd(**{'class':'form-control','aria-describedby':'passhlp','placeholder':'Password'}) }}
      {% if form.passwd.errors %}
      <ul class="form-text text-danger">
      {% for error in form.passwd.errors %}<li>{{ error }}</li>{% endfor %}
      </ul>
      {% else %} 
      <small id=passhlp" class="form-text text-muted">Enter your password.</small>
      {% endif %}
    </div>

	{% if cred_error %}
	<div class="alert alert-danger">
	Invalid username or password, please retry!
	</div>
	{% endif %}
	
    <button type="submit" class="btn btn-primary">Login</button>
  </form>
  <p>
  Not registered? Register <a href="{{ url_for("login.register_page") }}">here</a>!
  </p>
  </div>
  </div>
  </body>
</html>

myapp/templates/other.html
<!DOCTYPE html>
<html lang="el">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <link rel="stylesheet" href="static/bootstrap.min.css">
  </head>
  <body>
  <div class="row">
  <div class="col-md-6 offset-md-3">
  <h4>Other page</h4>
  <p>
  User: {{ current_user.user_record['username']|safe}}
  </p>
  <p>
  Check <a href="{{ url_for("hello.index_page") }}">index</a> page!
  </p>
  <p>
  <a class="btn btn-primary" href="{{ url_for("login.logout_page") }}">Logout</a>
  </p>
  </div>
  </div>
  </body>
</html>

myapp/templates/register.html
<!DOCTYPE html>
<html lang="el">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <link rel="stylesheet" href="static/bootstrap.min.css">
  </head>
  <body>
  <div class="row">
  <div class="col-md-6 offset-md-3">
  <h4>User Registration</h4>
  <form method="POST" action="">
    {{ form.hidden_tag() }}    {# this takes care of Flask-WTF csrf token too #}
    <div class="form-group">
      {{ form.username(**{'class':'form-control','aria-describedby':'userhlp','placeholder':'Username'}) }}
      {% if form.username.errors %}
      <ul class="form-text text-danger">
      {% for error in form.username.errors %}<li>{{ error }}</li>{% endfor %}
      </ul>
      {% else %} 
      <small id=userhlp" class="form-text text-muted">Select your desired username.</small>
      {% endif %}
    </div>

    <div class="form-group">
      {{ form.passwd(**{'class':'form-control','aria-describedby':'passhlp','placeholder':'Password'}) }}
      {% if form.passwd.errors %}
      <ul class="form-text text-danger">
      {% for error in form.passwd.errors %}<li>{{ error }}</li>{% endfor %}
      </ul>
      {% else %} 
      <small id=passhlp" class="form-text text-muted">Choose your password.</small>
	  {% endif %}
    </div>

    <div class="form-group">
      {{ form.passwd2(**{'class':'form-control','aria-describedby':'pass2hlp','placeholder':'Re-enter Password'}) }}
      {% if form.passwd2.errors %}
      <ul class="form-text text-danger">
      {% for error in form.passwd2.errors %}<li>{{ error }}</li>{% endfor %}
      </ul>
      {% else %} 
      <small id=pass2hlp" class="form-text text-muted">Enter your password again to validate entry.</small>
      {% endif %} 
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
  </form>
  </div>
  </div>
  </body>
</html>